//! FFI bindings to the Microsoft Cognitive Services Speech SDK C API.
//!
//! The actual bindings are generated by `bindgen` during build (see `build.rs`).
//! When `MS_COG_SVC_SPEECH_SKIP_BINDGEN=1`, pre-generated bindings are used.
#![allow(warnings)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
include!("ffi/bindings.rs");

// Manual type aliases matching the C SDK's #define types
pub type SPXPROPERTYBAGHANDLE = AZAC_HANDLE;
pub type SPXHANDLE = AZAC_HANDLE;
pub type SPXHR = AZACHR;

// 函数式宏 bindgen 无法生成，手动补充。
// SPXERR_BUFFER_TOO_SMALL = AZAC_ERR_BUFFER_TOO_SMALL = __AZAC_ERRCODE_FAILED(0x019) = 0x019
pub const SPXERR_BUFFER_TOO_SMALL: usize = 0x019;

use log::*;
use std::fmt::Debug;
use std::fmt::Display;
use std::fmt::Formatter;
use std::os::raw::c_char;

pub const NULL_C_STR_PTR: *const c_char = 0 as *const c_char;

/// RAII wrapper around native C SDK handles.
///
/// Automatically calls the release function when dropped,
/// ensuring native resources are properly freed.
#[derive(Debug)]
pub struct SmartHandle<T: Copy + Debug> {
    inner: T,
    release_fn: unsafe extern "C" fn(T) -> SPXHR,
    name: &'static str,
}

impl<T: Copy + Debug> SmartHandle<T> {
    #[inline(always)]
    pub fn create(
        name: &'static str,
        handle: T,
        release_fn: unsafe extern "C" fn(T) -> SPXHR,
    ) -> SmartHandle<T> {
        let result = SmartHandle {
            inner: handle,
            release_fn,
            name,
        };
        trace!("Create SmartHandle {}.", result);
        result
    }

    #[inline(always)]
    pub fn inner(&self) -> T {
        self.inner
    }
}

impl<T: Copy + Debug> Drop for SmartHandle<T> {
    fn drop(&mut self) {
        trace!("Drop SmartHandle {}.", self);
        let hr = unsafe { (self.release_fn)(self.inner) };
        if hr != SPX_NOERROR as usize {
            error!("cannot release SmartHandle {}, err={}", self, hr);
        }
    }
}

impl<T: Copy + Debug> Display for SmartHandle<T> {
    fn fmt(&self, f: &mut Formatter) -> std::fmt::Result {
        write!(f, "{}{{{:?}}}", self.name, self.inner)
    }
}

/// Safety: handles are opaque pointers safe to send across threads.
unsafe impl<T: Copy + Debug> Send for SmartHandle<T> {}
